# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94c0ac2b30efa92fd543633917ce821158849af68e0574a6732a2119fe6b615f521ef2e1d1de48f0a06306da95bec36b7afe1083e897b14962ace240cd1fe576

test:
  secret_key_base: 39ff22059d0b6495bff825509bf969deaf6eb48daefa5e0938a9295a92e17ea5e92139a4c020df7301709899282acc2184a62b79de630659f6f7eb504948c680

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
